export const teamMembers = [
  {
    id: "maya",
    name: "Maya Chen",
    role: "Incident commander",
    initials: "MC",
  },
  {
    id: "leo",
    name: "Leo Andersson",
    role: "Platform engineer",
    initials: "LA",
  },
  {
    id: "nora",
    name: "Nora Patel",
    role: "Product engineer",
    initials: "NP",
  },
  {
    id: "sam",
    name: "Sam Rivera",
    role: "Support lead",
    initials: "SR",
  },
];

export const services = [
  {
    id: "payments",
    name: "Payments",
    owner: "Revenue Systems",
    tier: "Tier 1",
    status: "degraded",
    slo: "99.95%",
    openIncidents: 1,
    lastDeploy: "2026-08-16T12:25:00.000Z",
  },
  {
    id: "public-api",
    name: "Public API",
    owner: "Platform",
    tier: "Tier 1",
    status: "healthy",
    slo: "99.90%",
    openIncidents: 0,
    lastDeploy: "2026-08-17T06:10:00.000Z",
  },
  {
    id: "worker-queue",
    name: "Worker Queue",
    owner: "Automation",
    tier: "Tier 2",
    status: "degraded",
    slo: "99.50%",
    openIncidents: 1,
    lastDeploy: "2026-08-15T17:40:00.000Z",
  },
  {
    id: "customer-app",
    name: "Customer App",
    owner: "Experience",
    tier: "Tier 2",
    status: "healthy",
    slo: "99.70%",
    openIncidents: 0,
    lastDeploy: "2026-08-16T19:05:00.000Z",
  },
];

export const runbooks = [
  {
    id: "checkout-latency",
    title: "Checkout latency above SLO",
    summary: "Triage payment processor latency, queue depth, and customer-facing checkout health.",
    serviceId: "payments",
    defaultSeverity: "SEV-2",
    estimatedMinutes: 35,
    tags: ["payments", "latency", "customer-impact"],
    steps: [
      {
        id: "latency-confirm",
        title: "Confirm customer impact",
        detail: "Compare checkout latency, error rate, and successful payment volume across the last 15 minutes.",
        role: "Incident commander",
        required: true,
        timeboxMinutes: 5,
      },
      {
        id: "processor-health",
        title: "Check processor status",
        detail: "Review payment provider status pages and recent webhook delivery failures.",
        role: "Platform engineer",
        required: true,
        timeboxMinutes: 8,
      },
      {
        id: "queue-drain",
        title: "Inspect queue backlog",
        detail: "Check worker queue depth, retry volume, and oldest unprocessed payment job.",
        role: "Platform engineer",
        required: true,
        timeboxMinutes: 10,
      },
      {
        id: "support-update",
        title: "Prepare support note",
        detail: "Draft short customer-support guidance with affected window and known workaround.",
        role: "Support lead",
        required: false,
        timeboxMinutes: 12,
      },
    ],
  },
  {
    id: "api-error-spike",
    title: "Public API error spike",
    summary: "Isolate a sudden 5xx increase by deployment, endpoint, tenant, and dependency.",
    serviceId: "public-api",
    defaultSeverity: "SEV-2",
    estimatedMinutes: 30,
    tags: ["api", "errors", "rollback"],
    steps: [
      {
        id: "api-scope",
        title: "Scope affected endpoints",
        detail: "Group errors by endpoint, status code, tenant, and region.",
        role: "Incident commander",
        required: true,
        timeboxMinutes: 7,
      },
      {
        id: "api-deploy",
        title: "Compare deploy window",
        detail: "Check whether the spike aligns with a recent deploy, migration, or config change.",
        role: "Platform engineer",
        required: true,
        timeboxMinutes: 8,
      },
      {
        id: "api-rollback",
        title: "Decide rollback path",
        detail: "Prepare rollback or feature flag disablement for the most likely change.",
        role: "Product engineer",
        required: true,
        timeboxMinutes: 15,
      },
    ],
  },
  {
    id: "queue-stall",
    title: "Worker queue stalled",
    summary: "Recover delayed jobs when queue processing stops or retries climb quickly.",
    serviceId: "worker-queue",
    defaultSeverity: "SEV-3",
    estimatedMinutes: 25,
    tags: ["jobs", "queue", "automation"],
    steps: [
      {
        id: "queue-depth",
        title: "Measure queue depth",
        detail: "Capture waiting, active, delayed, failed, and oldest job age.",
        role: "Platform engineer",
        required: true,
        timeboxMinutes: 5,
      },
      {
        id: "worker-logs",
        title: "Inspect worker logs",
        detail: "Look for repeated exceptions, connection resets, or lock contention.",
        role: "Platform engineer",
        required: true,
        timeboxMinutes: 10,
      },
      {
        id: "job-replay",
        title: "Replay failed sample",
        detail: "Run one failed job safely in isolation and record the result.",
        role: "Product engineer",
        required: false,
        timeboxMinutes: 10,
      },
    ],
  },
];

export const initialIncidents = [
  {
    id: "inc-1042",
    title: "Checkout latency above SLO",
    serviceId: "payments",
    runbookId: "checkout-latency",
    severity: "SEV-2",
    status: "active",
    commanderId: "maya",
    startedAt: "2026-08-17T07:18:00.000Z",
    resolvedAt: null,
    summary: "",
    impactSummary: "",
    rootCause: "",
    resolutionSummary: "",
    followUpActions: "",
    steps: [
      {
        id: "inc-1042-latency-confirm",
        sourceStepId: "latency-confirm",
        title: "Confirm customer impact",
        detail: "Compare checkout latency, error rate, and successful payment volume across the last 15 minutes.",
        role: "Incident commander",
        required: true,
        status: "done",
        assigneeId: "maya",
        completedAt: "2026-08-17T07:24:00.000Z",
      },
      {
        id: "inc-1042-processor-health",
        sourceStepId: "processor-health",
        title: "Check processor status",
        detail: "Review payment provider status pages and recent webhook delivery failures.",
        role: "Platform engineer",
        required: true,
        status: "in_progress",
        assigneeId: "leo",
        completedAt: null,
      },
      {
        id: "inc-1042-queue-drain",
        sourceStepId: "queue-drain",
        title: "Inspect queue backlog",
        detail: "Check worker queue depth, retry volume, and oldest unprocessed payment job.",
        role: "Platform engineer",
        required: true,
        status: "pending",
        assigneeId: "leo",
        completedAt: null,
      },
      {
        id: "inc-1042-support-update",
        sourceStepId: "support-update",
        title: "Prepare support note",
        detail: "Draft short customer-support guidance with affected window and known workaround.",
        role: "Support lead",
        required: false,
        status: "pending",
        assigneeId: "sam",
        completedAt: null,
      },
    ],
    timeline: [
      {
        id: "evt-1042-1",
        type: "opened",
        message: "Incident opened for Payments.",
        actorId: "maya",
        createdAt: "2026-08-17T07:18:00.000Z",
      },
      {
        id: "evt-1042-2",
        type: "step_done",
        message: "Confirm customer impact completed.",
        actorId: "maya",
        createdAt: "2026-08-17T07:24:00.000Z",
      },
      {
        id: "evt-1042-3",
        type: "status",
        message: "Payment processor latency confirmed in EU region.",
        actorId: "leo",
        createdAt: "2026-08-17T07:31:00.000Z",
      },
    ],
    notes: [
      {
        id: "note-1042-1",
        body: "Support has a draft customer update ready if latency stays elevated.",
        authorId: "sam",
        createdAt: "2026-08-17T07:34:00.000Z",
      },
    ],
  },
  {
    id: "inc-1041",
    title: "Worker queue retry volume elevated",
    serviceId: "worker-queue",
    runbookId: "queue-stall",
    severity: "SEV-3",
    status: "monitoring",
    commanderId: "nora",
    startedAt: "2026-08-17T05:42:00.000Z",
    resolvedAt: null,
    summary: "",
    impactSummary: "Retry latency was elevated for background automation jobs, but customer-facing requests stayed healthy.",
    rootCause: "A worker pool deploy increased lock contention on retry-heavy job batches.",
    resolutionSummary: "Reduced concurrency, drained the stuck batch, and left queue depth under watch.",
    followUpActions: "Add lock-wait alerts and test high-retry batches before future worker deploys.",
    steps: [
      {
        id: "inc-1041-queue-depth",
        sourceStepId: "queue-depth",
        title: "Measure queue depth",
        detail: "Capture waiting, active, delayed, failed, and oldest job age.",
        role: "Platform engineer",
        required: true,
        status: "done",
        assigneeId: "leo",
        completedAt: "2026-08-17T05:51:00.000Z",
      },
      {
        id: "inc-1041-worker-logs",
        sourceStepId: "worker-logs",
        title: "Inspect worker logs",
        detail: "Look for repeated exceptions, connection resets, or lock contention.",
        role: "Platform engineer",
        required: true,
        status: "done",
        assigneeId: "leo",
        completedAt: "2026-08-17T06:02:00.000Z",
      },
      {
        id: "inc-1041-job-replay",
        sourceStepId: "job-replay",
        title: "Replay failed sample",
        detail: "Run one failed job safely in isolation and record the result.",
        role: "Product engineer",
        required: false,
        status: "done",
        assigneeId: "nora",
        completedAt: "2026-08-17T06:11:00.000Z",
      },
    ],
    timeline: [
      {
        id: "evt-1041-1",
        type: "opened",
        message: "Incident opened for Worker Queue.",
        actorId: "nora",
        createdAt: "2026-08-17T05:42:00.000Z",
      },
      {
        id: "evt-1041-2",
        type: "monitoring",
        message: "Queue depth recovered; monitoring retry rate.",
        actorId: "leo",
        createdAt: "2026-08-17T06:18:00.000Z",
      },
    ],
    notes: [],
  },
  {
    id: "inc-1039",
    title: "Public API 5xx spike after deploy",
    serviceId: "public-api",
    runbookId: "api-error-spike",
    severity: "SEV-2",
    status: "resolved",
    commanderId: "maya",
    startedAt: "2026-08-16T21:05:00.000Z",
    resolvedAt: "2026-08-16T21:41:00.000Z",
    summary: "Rolled back a config change that caused validation failures on token refresh.",
    impactSummary: "Some API clients saw elevated 5xx responses on token refresh for 36 minutes.",
    rootCause: "A config rollout tightened validation before all tenants had the matching metadata.",
    resolutionSummary: "Rolled back the config change and replayed failed refresh attempts.",
    followUpActions: "Gate config validation behind a staged tenant rollout and add canary coverage for token refresh.",
    steps: [],
    timeline: [
      {
        id: "evt-1039-1",
        type: "opened",
        message: "Incident opened for Public API.",
        actorId: "maya",
        createdAt: "2026-08-16T21:05:00.000Z",
      },
      {
        id: "evt-1039-2",
        type: "resolved",
        message: "Incident resolved after config rollback.",
        actorId: "maya",
        createdAt: "2026-08-16T21:41:00.000Z",
      },
    ],
    notes: [],
  },
];
